name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  compile-and-test:
    name: Compile and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-repo-

      - name: "Test"
        run: mvn test
